### ISSUE TITLE
OpenToonz freezes when press the + key in Ubuntu 18.04 

### ISSUE THREAD

**Issue by ghost** [snapcrafters/opentoonz#1]
Well that, I was testing the candidate release, and everything worked fine, until I pressed the + key and it's stopped, then the message came out that the program had stopped responding and had to be killed.
Try other keys and shortcuts and everything is fine.
The error is only when I press +.

**Comment by merlijn-sebrechts** [comment]
I tested this today and pressing `+` works. It seems to zoom in on the canvas. @igorljubuncic I propose to close this issue, if the problem re-appears, feel free to comment and re-open this issue.
