### ISSUE TITLE
update to 1.2.1

### ISSUE THREAD

**Issue by pixelr0** [snapcrafters/opentoonz#2]
the latest version is 1.2.1
they snap is 1.2.0

channels:                    
  stable:    –               
  candidate: 1.2.0 (2) 160MB -
  beta:      ↑               
  edge:      1.2.0 (7) 160MB -

**Comment by Lvaskz** [comment]
hi, update to 1.3
see
![imagen](https://user-images.githubusercontent.com/29207169/52150719-708eb180-2636-11e9-908b-21fe09e24c5c.png)
