### ISSUE TITLE
Fails to start in Wayland session

### ISSUE THREAD

**Issue by dayrover** [snapcrafters/opentoonz#5]
In a Wayland session follow error is seen:

> This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

This is a common problem with snap using a modern qt. See [https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055](https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055)

**Comment by Sentient07** [comment]
Hello,

I'm facing this error message while trying to install cloudcompare. Is any fix available for this issue?
